name: Releases
on: [workflow_dispatch]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          version-file: './package.json,./package-lock.json'

      - run: echo "RELEASE_BODY=${{ steps.changelog.outputs.clean_changelog }}" >> $GITHUB_ENV
      - run: echo "RELEASE_TAG=${{ steps.changelog.outputs.tag }}" >> $GITHUB_ENV

      - run: node index.js