name: Releases
on: 
  push:
    tags:
      - "*"

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}0

      # - name: conventional Changelog Action
      #   id: changelog
      #   uses: TriPSs/conventional-changelog-action@v3.7.1
      #   with:
      #     skip-version-file: "true"
      #     skip-commit: "true"
      #     output-file: "false"
      #     github-token: ${{ secrets.RELEASE_TOKEN }}
          # version-file: './package.json,./package-lock.json'

      
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: subhanmahmood/first-action@v1.1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"