name: Releases
on: [workflow_dispatch]
  # push:
  #   tags:
  #     - "*"

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure service specific deployment settings
        run: |
          export CURRENT_TAG=${GITHUB_REF#"refs/*/"}
          echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV

      - name: Retrieve release details
        id: release-details
        run: |
          echo $GITHUB_REF
          echo $CURRENT_TAG
          RELEASE_TITLE=$(gh release view $CURRENT_TAG --json tagName --jq .tagName)

          RELEASE_BODY=$(gh release view $CURRENT_TAG --json body --jq .body)
          RELEASE_BODY="${RELEASE_BODY//'%'/'%25'}"
          RELEASE_BODY="${RELEASE_BODY//$'\n'/'%0A'}"
          RELEASE_BODY="${RELEASE_BODY//$'\r'/'%0D'}"

          echo "::set-output name=RELEASE_TITLE::$RELEASE_TITLE"
          echo "::set-output name=RELEASE_BODY::$RELEASE_BODY"
        env:
          CURRENT_TAG: ${{ env.CURRENT_TAG }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
