name: Releases
on: [workflow_dispatch]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          skip-version-file: true
          skip-commit: true
          github-token: ${{ secrets.RELEASE_TOKEN }}
          version-file: './package.json,./package-lock.json'

      - run: node index.js "${{ steps.changelog.outputs.clean_changelog }}" "${{ steps.changelog.outputs.tag }}"