name: Releases
on: 
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      # Use LTS node version
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Get release details
        id: release_details
        run: |
          # Parse changelog
          CHANGELOG=$(./utils/parse_changelog.sh)
          MARKDOWN_CHANGELOG=$(echo $CHANGELOG | ./utils/markdown_to_html.sh)
          echo "::set-output name=changelog::$CHANGELOG"
          echo "::set-output name=markdown::"$MARKDOWN_CHANGELOG""
          echo "::set-output name=version::${GITHUB_REF#refs/*/}"

      # Create changelog
      - name: Changelog
        id: changelog
        run: |
          # sanity check
          echo "Got changelog: ${{steps.release_details.outputs.changelog}}"
          echo "Got markdown of changelog: ${{steps.release_details.outputs.markdown}}"
      # Create github release
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ steps.release_details.outputs.changelog }}
          draft: false
          prerelease: false

      # - name: Slack Notify
      #   uses: rtCamp/action-slack-notify@v2.2.0
      #   env:
      #     SLACK_ICON: https://production-orderpay.s3.amazonaws.com/brand/images/logo/image/7e9db92f-be27-4d2c-a124-77251c8d11d6.png
      #     SLACK_CHANNEL: op_deployment_frontend
      #     SLACK_USERNAME: Bishop
      #     SLACK_TITLE: 'OrderPay Web Ordering release ${{ steps.release_details.outputs.version }} :bookmark:'
      #     SLACK_MESSAGE: ${{steps.release_details.outputs.changelog}}
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEPLOYMENT }}
      #     MSG_MINIMAL: ref, commit

  send-message:
    needs: create-release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Configure service specific deployment settings
        run: |
          export CURRENT_TAG=${GITHUB_REF#refs/*/}
          echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV

      - name: Retrieve release details
        id: release-details
        run: |
          echo $CURRENT_TAG
          RELEASE_TITLE=$(gh release view $CURRENT_TAG --json tagName --jq .tagName)

          RELEASE_BODY=$(gh release view $CURRENT_TAG --json body --jq .body)
          RELEASE_BODY="${RELEASE_BODY//'%'/'%25'}"
          RELEASE_BODY="${RELEASE_BODY//$'\n'/'%0A'}"
          RELEASE_BODY="${RELEASE_BODY//$'\r'/'%0D'}"

          echo "::set-output name=RELEASE_TITLE::$RELEASE_TITLE"
          echo "::set-output name=RELEASE_BODY::$RELEASE_BODY"
        env:
          CURRENT_TAG: ${{ env.CURRENT_TAG }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        
      - name: Convert Github release notes markdown to Slack markdown
        id: formatted-release-body
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        with:
          text: ${{ steps.release-details.outputs.RELEASE_BODY }}

      - uses: homeday-de/slack-release-bot-action@main
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          title: "OrderPay Web Ordering ${{ steps.extract_branch.outputs.branch }} ${{ steps.release-details.outputs.RELEASE_TITLE }}"
          body: ${{ steps.formatted-release-body.outputs.text }}
          context: "OrderPay Web Ordering"

