name: Releases
on: 
  push:
    tags:
      - "*"

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}0

      - name: Configure service specific settings
      - run: |
        export CURRENT_TAG=${GITHUB_REF#"refs/tags/"}
        echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV