name: Releases
on: 
  push:
    tags:
      - "*"

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure service specific settings
        - run: |
            export CURRENT_TAG=${GITHUB_REF#"refs/tags/"}
            echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV
            fi

      - name: Retrieve release details
        id: release-details
        run: |
          RELEASE_TITLE=$(gh release view $CURRENT_TAG --json tagName --jq .tagName)

          RELEASE_BODY=$(gh release view $CURRENT_TAG --json body --jq .body)
          RELEASE_BODY="${RELEASE_BODY//'%'/'%25'}"
          RELEASE_BODY="${RELEASE_BODY//$'\n'/'%0A'}"
          RELEASE_BODY="${RELEASE_BODY//$'\r'/'%0D'}"

          echo "::set-output name=RELEASE_TITLE::$RELEASE_TITLE"
          echo "::set-output name=RELEASE_BODY::$RELEASE_BODY"
        env:
          CURRENT_TAG: ${{ env.CURRENT_TAG }}
          GITHUB_TOKEN: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}